export { DynamicMapService } from '@/DynamicMapService'
export { TiledMapService } from '@/TiledMapService'
export { ImageService } from '@/ImageService'
export { VectorBasemapStyle } from '@/VectorBasemapStyle'
export { VectorTileService } from '@/VectorTileService'
export { FeatureService } from '@/FeatureService.pending'
export { cleanTrailingSlash, getServiceDetails, updateAttribution } from '@/utils'
export * from '@/types/types'
